name: Playwright CI Pipeline

on:

  workflow_dispatch:

    inputs:

      environment:

        description: 'Select Environment'

        required: true

        default: 'qa'

        type: choice

        options:
          - dev
          - qa
          - uat

  push:
    branches:
      - main
      - develop

  pull_request:
    branches:
      - main

  schedule:
    - cron: '0 0 * * *'

jobs:

  playwright-test:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install Dependencies
        run: npm install

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Run Playwright Tests

        env:
          TEST_ENV: ${{ github.event.inputs.environment }}

        run: npx playwright test

      - name: Upload Playwright Report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report
          path: playwright-report/