name: Regression Tests

on:
  workflow_dispatch:

  pull_request:
    branches:
      - main

  schedule:
    - cron: '0 0 * * *'

jobs:
  regression-test:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install Dependencies
        run: npm install

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Run Regression Tests
        env:
            TEST_PASSWORD: ${{ secrets.QA_PASSWORD }}
        run: npx playwright test --grep "@regression"